spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 4c9q83otofd09727mbsm3jbjom
            client-secret: 3quv4karlsm3tdo6mvhk5f2110n67ko8od5ircqm1oe8htgaoon
            client-name: mks-ssopoc
            provider: cognito
            scope: openid
            redirect-uri-template: http://localhost:8080/login/oauth2/code/cognito
            authorization-grant-type: authorization_code
        provider:
          cognito:
            authorization-uri: https://mks-ssopoc.auth.ap-southeast-1.amazoncognito.com/oauth2/authorize
            token-uri: https://mks-ssopoc.auth.ap-southeast-1.amazoncognito.com/oauth2/token
            user-info-uri: https://mks-ssopoc.auth.ap-southeast-1.amazoncognito.com/oauth2/userInfo
            jwk-set-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_r3FfzEg1D/.well-known/jwks.json
            user-name-attribute: cognito:username
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
server:
  port: 8080
  error:
    whitelabel:
      enabled: true